version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - db-data:/var/lib/postgres/data/
    expose:
      - 5432
    env_file: ./server/.env.prod

  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: flask --app app.main run --host=0.0.0.0
    command: gunicorn --bind 0.0.0.0:5000 "app.main:create_app()"
    # ports:
    #   - "5000:5000"
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
    expose:
      - 5000
    volumes:
      - static_volume:/app/server/static

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - static_volume:/app/nginx/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  db-data:
  static_volume:
