version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - db-data:/var/lib/postgres/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: todo-db

volumes:
  db-data:
