GET http://dev.localhost:5000/api/getcsrf
Accept: application/json

###
POST http://dev.localhost:5000/api/auth/register
Content-Type: application/json
X-CSRFToken: ImUxMGM0MTBkNDI1YmE3NTE4NTgxOGE3MzQ3OGVkOGM0NjkzZDM3YWIi.Y47UrA.Pxe0_w965n4YfzoQqG7IS2edfsQ

{
  "email": "email1@example"
}

###
